[package]
name = "store"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.21.3"
serial_test = "2.0.0"
sqlite = "0.31.0"
api = { path = '../api'}
identity = { path = '../identity' }