[package]
name = "protocol"
version = "0.1.0"
edition = "2024"

[dependencies]
crypto = { path = '../crypto', features = ["encryption"] }
logger = { path = '../logger' }
hex = "0.4.3"
once_cell = "1.21.3"
secrets = "1.2.0"