[package]
name = "logger"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.31"
dotenv = "0.15.0"
dotenv_codegen = "0.15.0"
fern = "0.6.2"
home = "0.5.5"
log = "0.4.20"
