[package]
name = "identity"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crypto = { path = '../crypto', features = ["encryption"] }
logger = { path = '../logger' }
hex = "0.4.3"

